PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <https://schema.org/>
PREFIX domain: <http://ilearn.ilabt.imec.be/vocab/curr1/>

CONSTRUCT {
    ?curr rdf:type schema:DefinedTermSet .
    ?curr schema:name ?label .
    ?curr schema:description ?def .
    ?curr schema:isPartOf ?topCurr .

}
WHERE {
    ?curr skos:inScheme domain:_scheme .
    ?curr skos:prefLabel ?label .
    ?curr skos:definition ?def .
    OPTIONAL {?curr skos:broader ?topCurr .}
}