PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?chapter WHERE {
    ?chapter rdf:type bibo:Chapter .
    ?chapter bibo:pageStart ?startPage .
    ?chapter bibo:pageEnd ?endPage .
    FILTER(?startPage < ?page || ?startPage = ?page) .
    FILTER(?endPage > ?page || ?endPage = ?page) .
  {
    ?chapter dcterms:isPartOf ?material .
  } UNION {
    ?chapter dcterms:isPartOf ?section .
    ?section dcterms:isPartOf ?material .
  }
}
LIMIT 1